import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { Copy, Eye } from "lucide-react";
import { toast } from "sonner";

interface Template {
  id: string;
  name: string;
  description: string;
  headerText: string;
  footerText: string;
  fontSize: string;
  fontFamily: string;
  lineSpacing: string;
  colorScheme: string;
}

const BUILT_IN_TEMPLATES: Template[] = [
  {
    id: "github-ready",
    name: "GitHub-Ready",
    description: "Optimized for GitHub markdown rendering with clean formatting",
    headerText: "",
    footerText: "Generated by The Repo Scribe",
    fontSize: "normal",
    fontFamily: "sans-serif",
    lineSpacing: "1.5",
    colorScheme: "default",
  },
  {
    id: "legal-review",
    name: "Legal Review",
    description: "Professional legal document format with formal spacing and margins",
    headerText: "LEGAL DOCUMENT - DRAFT FOR REVIEW",
    footerText: "This document was generated by AI and should be reviewed by legal counsel before use.",
    fontSize: "normal",
    fontFamily: "serif",
    lineSpacing: "2",
    colorScheme: "professional",
  },
  {
    id: "developer-friendly",
    name: "Developer Friendly",
    description: "Code-focused format with monospace fonts and compact spacing",
    headerText: "",
    footerText: "Repository Documentation",
    fontSize: "small",
    fontFamily: "monospace",
    lineSpacing: "1.5",
    colorScheme: "minimal",
  },
  {
    id: "academic",
    name: "Academic",
    description: "Formal academic paper format with double spacing and citations",
    headerText: "ACADEMIC DOCUMENTATION",
    footerText: "Generated by The Repo Scribe AI system",
    fontSize: "normal",
    fontFamily: "serif",
    lineSpacing: "2",
    colorScheme: "professional",
  },
  {
    id: "minimal",
    name: "Minimal",
    description: "Clean, minimal format for quick reading and printing",
    headerText: "",
    footerText: "",
    fontSize: "small",
    fontFamily: "sans-serif",
    lineSpacing: "1",
    colorScheme: "minimal",
  },
];

interface TemplateLibraryProps {
  onApplyTemplate?: (template: Template) => void;
}

export default function TemplateLibrary({ onApplyTemplate }: TemplateLibraryProps) {
  const [selectedTemplate, setSelectedTemplate] = useState<Template | null>(null);
  const [showPreview, setShowPreview] = useState(false);

  const handleApply = (template: Template) => {
    if (onApplyTemplate) {
      onApplyTemplate(template);
      toast.success(`Applied ${template.name} template`);
    }
  };

  const handleDuplicate = (template: Template) => {
    // Copy template settings to clipboard as JSON
    const templateJson = JSON.stringify(template, null, 2);
    navigator.clipboard.writeText(templateJson);
    toast.success(`Copied ${template.name} template settings`);
  };

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {BUILT_IN_TEMPLATES.map((template) => (
          <Card
            key={template.id}
            className="hover:shadow-lg transition-shadow cursor-pointer"
            onClick={() => setSelectedTemplate(template)}
          >
            <CardHeader>
              <CardTitle className="text-lg">{template.name}</CardTitle>
              <CardDescription>{template.description}</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex flex-wrap gap-2">
                <Badge variant="outline" className="text-xs">
                  {template.fontSize}
                </Badge>
                <Badge variant="outline" className="text-xs">
                  {template.fontFamily}
                </Badge>
                <Badge variant="outline" className="text-xs">
                  {template.lineSpacing}x spacing
                </Badge>
              </div>
              <div className="flex gap-2">
                <Button
                  size="sm"
                  variant="outline"
                  className="flex-1"
                  onClick={(e) => {
                    e.stopPropagation();
                    setShowPreview(true);
                  }}
                >
                  <Eye className="w-4 h-4 mr-1" />
                  Preview
                </Button>
                <Button
                  size="sm"
                  variant="default"
                  className="flex-1"
                  onClick={(e) => {
                    e.stopPropagation();
                    handleApply(template);
                  }}
                >
                  Apply
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Template Details Dialog */}
      <Dialog open={selectedTemplate !== null} onOpenChange={(open) => !open && setSelectedTemplate(null)}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>{selectedTemplate?.name}</DialogTitle>
            <DialogDescription>{selectedTemplate?.description}</DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="text-sm font-medium">Font Family</label>
                <p className="text-sm text-muted-foreground">{selectedTemplate?.fontFamily}</p>
              </div>
              <div>
                <label className="text-sm font-medium">Font Size</label>
                <p className="text-sm text-muted-foreground">{selectedTemplate?.fontSize}</p>
              </div>
              <div>
                <label className="text-sm font-medium">Line Spacing</label>
                <p className="text-sm text-muted-foreground">{selectedTemplate?.lineSpacing}x</p>
              </div>
              <div>
                <label className="text-sm font-medium">Color Scheme</label>
                <p className="text-sm text-muted-foreground">{selectedTemplate?.colorScheme}</p>
              </div>
            </div>

            {selectedTemplate?.headerText && (
              <div>
                <label className="text-sm font-medium">Header</label>
                <p className="text-sm text-muted-foreground italic">{selectedTemplate.headerText}</p>
              </div>
            )}

            {selectedTemplate?.footerText && (
              <div>
                <label className="text-sm font-medium">Footer</label>
                <p className="text-sm text-muted-foreground italic">{selectedTemplate.footerText}</p>
              </div>
            )}

            <div className="flex gap-2 pt-4">
              <Button
                variant="outline"
                className="flex-1"
                onClick={() => selectedTemplate && handleDuplicate(selectedTemplate)}
              >
                <Copy className="w-4 h-4 mr-2" />
                Duplicate
              </Button>
              <Button
                className="flex-1"
                onClick={() => {
                  if (selectedTemplate) {
                    handleApply(selectedTemplate);
                    setSelectedTemplate(null);
                  }
                }}
              >
                Apply Template
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
