export interface BuiltInTemplate {
  name: string;
  description: string;
  headerText: string;
  footerText: string;
  includeMetadata: boolean;
  includeTableOfContents: boolean;
  fontSize: "small" | "normal" | "large";
  fontFamily: "sans-serif" | "serif" | "monospace";
  lineSpacing: "1" | "1.5" | "2";
  pageMargins: string;
  colorScheme: "default" | "professional" | "minimal" | "vintage";
}

export const BUILT_IN_TEMPLATES: Record<string, BuiltInTemplate> = {
  "github-ready": {
    name: "GitHub-Ready",
    description: "Optimized for GitHub markdown rendering with clean formatting",
    headerText: "",
    footerText: "---\n*Generated by The Repo Scribe*",
    includeMetadata: true,
    includeTableOfContents: false,
    fontSize: "normal",
    fontFamily: "sans-serif",
    lineSpacing: "1.5",
    pageMargins: "1in",
    colorScheme: "default",
  },
  "legal-review": {
    name: "Legal Review",
    description: "Professional legal document format with formal spacing and margins",
    headerText: "LEGAL DOCUMENT - DRAFT FOR REVIEW",
    footerText:
      "---\n*This document was generated by AI and should be reviewed by legal counsel before use.*",
    includeMetadata: true,
    includeTableOfContents: true,
    fontSize: "normal",
    fontFamily: "serif",
    lineSpacing: "2",
    pageMargins: "1.25in",
    colorScheme: "professional",
  },
  "developer-friendly": {
    name: "Developer Friendly",
    description: "Code-focused format with monospace fonts and compact spacing",
    headerText: "",
    footerText: "---\n*Repository Documentation*",
    includeMetadata: true,
    includeTableOfContents: false,
    fontSize: "small",
    fontFamily: "monospace",
    lineSpacing: "1.5",
    pageMargins: "0.75in",
    colorScheme: "minimal",
  },
  "academic": {
    name: "Academic",
    description: "Formal academic paper format with double spacing and citations",
    headerText: "ACADEMIC DOCUMENTATION",
    footerText:
      "---\n*This document was generated by The Repo Scribe AI system*",
    includeMetadata: true,
    includeTableOfContents: true,
    fontSize: "normal",
    fontFamily: "serif",
    lineSpacing: "2",
    pageMargins: "1in",
    colorScheme: "professional",
  },
  "minimal": {
    name: "Minimal",
    description: "Clean, minimal format for quick reading and printing",
    headerText: "",
    footerText: "",
    includeMetadata: false,
    includeTableOfContents: false,
    fontSize: "small",
    fontFamily: "sans-serif",
    lineSpacing: "1",
    pageMargins: "0.5in",
    colorScheme: "minimal",
  },
};

export const TEMPLATE_KEYS = Object.keys(BUILT_IN_TEMPLATES) as Array<
  keyof typeof BUILT_IN_TEMPLATES
>;
