import { describe, expect, it } from "vitest";
import { exportAsDocx, exportAsHTML, exportAsMarkdown, exportAsPDF, exportAsText } from "./export";

const baseOptions = {
  content: "# Terms\n\nImportant terms.",
  filename: "terms",
  title: "TERMS_OF_SERVICE",
  docType: "TERMS_OF_SERVICE",
  repoUrl: "https://github.com/cass/repo-scribe",
  generatedAt: new Date("2026-08-19T12:00:00.000Z"),
};

describe("template-aware exports", () => {
  it("adds the default template header and footer to Markdown and plain-text exports", () => {
    const template = { headerText: "CONFIDENTIAL DRAFT", footerText: "Review with counsel", includeMetadata: 1 };

    expect(exportAsMarkdown({ ...baseOptions, template }).toString("utf-8")).toContain(
      "CONFIDENTIAL DRAFT\n\n# Terms\n\nImportant terms.\n\nReview with counsel"
    );
    expect(exportAsText({ ...baseOptions, template }).toString("utf-8")).toContain("Review with counsel");
  });

  it("removes the generated metadata header and adds a table of contents when the template requests it", () => {
    const markdown = exportAsMarkdown({
      ...baseOptions,
      content: "<!-- Generated by The Repo Scribe\nRepository: example\n-->\n\n# Terms\n\n## Scope\n\nImportant terms.",
      template: { includeMetadata: 0, includeTableOfContents: 1 },
    }).toString("utf-8");

    expect(markdown).not.toContain("Generated by The Repo Scribe");
    expect(markdown).toContain("## Table of Contents");
    expect(markdown).toContain("- [Terms](#terms)");
    expect(markdown).toContain("  - [Scope](#scope)");
  });

  it("honors a template that suppresses generated metadata and applies safe HTML presentation settings", () => {
    const html = exportAsHTML({
      ...baseOptions,
      template: {
        includeMetadata: 0,
        fontFamily: "serif",
        fontSize: "large",
        lineSpacing: "2",
        colorScheme: "vintage",
        pageMargins: "1in",
      },
    }).toString("utf-8");

    expect(html).not.toContain("Document Type:");
    expect(html).toContain("Georgia, 'Times New Roman', serif");
    expect(html).toContain("font-size: 18px");
    expect(html).toContain("color: #981518");
  });

  it("escapes untrusted repository or model content before embedding it in HTML", () => {
    const html = exportAsHTML({ ...baseOptions, content: "# Heading\n\n<script>alert('nope')</script>" }).toString("utf-8");

    expect(html).toContain("&lt;script&gt;alert(&#039;nope&#039;)&lt;/script&gt;");
    expect(html).not.toContain("<script>alert('nope')</script>");
  });

  it("renders non-empty PDF and Word files with persisted typography settings", async () => {
    const template = {
      includeMetadata: 0,
      fontFamily: "monospace",
      fontSize: "large",
      lineSpacing: "2",
      pageMargins: "0.75in",
      colorScheme: "vintage",
    };
    const [pdf, docx] = await Promise.all([
      exportAsPDF({ ...baseOptions, template }),
      exportAsDocx({ ...baseOptions, template }),
    ]);

    expect(pdf.length).toBeGreaterThan(100);
    expect(docx.length).toBeGreaterThan(100);
  });
});
