import { z } from "zod";
import { invokeLLM } from "../_core/llm";
import { saveGeneration } from "../db";

const DOC_TYPES = [
  "README",
  "LICENSE",
  "CODE_OF_CONDUCT",
  "CONTRIBUTING",
  "SECURITY",
  "PRIVACY",
  "TERMS_OF_SERVICE",
] as const;

const TONES = [
  "Formal",
  "Professional",
  "Friendly",
  "Casual",
  "Laid-back",
  "Deadpool-cool",
] as const;

const LENGTHS = ["short", "medium", "long"] as const;

const generateDocumentSchema = z.object({
  repoUrl: z.string().url().regex(/^https:\/\/github\.com\/[^\/]+\/[^\/]+\/?$/),
  docType: z.enum(DOC_TYPES),
  tone: z.enum(TONES),
  length: z.enum(LENGTHS),
  repoMetadata: z.object({
    name: z.string(),
    description: z.string().optional(),
    language: z.string().optional(),
    license: z.string().optional(),
    topics: z.array(z.string()).optional(),
    readme: z.string().optional(),
  }),
});

type GenerateDocumentInput = z.infer<typeof generateDocumentSchema>;

function getLengthRange(length: string): string {
  switch (length) {
    case "short":
      return "500-700 words";
    case "medium":
      return "1000-1500 words";
    case "long":
      return "2000-3000 words";
    default:
      return "1000-1500 words";
  }
}

function getToneDescription(tone: string): string {
  const descriptions: Record<string, string> = {
    Formal:
      "Use formal, legal language with proper terminology and structure. Be precise and authoritative.",
    Professional:
      "Use professional language with clear structure. Balance formality with readability.",
    Friendly:
      "Use approachable, friendly language while maintaining professionalism. Make it easy to understand.",
    Casual:
      "Use casual, conversational language. Keep it relaxed but still professional.",
    "Laid-back":
      "Use laid-back, informal language. Make it feel natural and conversational.",
    "Deadpool-cool":
      "Use snarky, fourth-wall-aware language with razor wit and dry sarcasm. Include well-placed parentheticals and self-aware quips about how nobody reads these docs. Roast obvious nonsense and mock legalese while still writing it correctly. Never reference Deadpool, Wade Wilson, Marvel, Avengers, X-Men, chimichangas, katanas, or any copyrighted character/brand. Capture the merc-with-a-mouth energy without the IP.",
  };
  return descriptions[tone] || descriptions.Professional;
}

export async function generateDocument(
  input: GenerateDocumentInput,
  userId: number
): Promise<{ content: string; metadata: any }> {
  const validated = generateDocumentSchema.parse(input);
  const { repoUrl, docType, tone, length, repoMetadata } = validated;

  const lengthRange = getLengthRange(length);
  const toneDescription = getToneDescription(tone);

  const systemPrompt = `You are an expert technical and legal writer. Your task is to generate clean, professional Markdown documents for GitHub repositories.

IMPORTANT RULES:
1. Never invent verifiable facts. Use bracketed placeholders like [Contact Email], [Jurisdiction], [Your Company Name] for information you don't have.
2. Always include a disclaimer where relevant (especially for legal documents).
3. Write in valid Markdown format with proper heading hierarchy.
4. Use clear, well-structured sections.
5. Tone: ${toneDescription}
6. Target length: ${lengthRange}
7. Make the document practical and immediately usable.`;

  const userPrompt = `Generate a ${docType.replace(/_/g, " ")} document for the following GitHub repository:

Repository: ${repoMetadata.name}
URL: ${repoUrl}
${repoMetadata.description ? `Description: ${repoMetadata.description}` : ""}
${repoMetadata.language ? `Primary Language: ${repoMetadata.language}` : ""}
${repoMetadata.license ? `License: ${repoMetadata.license}` : ""}
${repoMetadata.topics && repoMetadata.topics.length > 0 ? `Topics: ${repoMetadata.topics.join(", ")}` : ""}

${repoMetadata.readme ? `README Preview:\n${repoMetadata.readme.substring(0, 1000)}...` : ""}

Generate a professional ${docType.replace(/_/g, " ")} document tailored to this repository. The document should be ready to use with minimal modifications.`;

  try {
    const response = await invokeLLM({
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
    });

    const messageContent = response.choices[0]?.message?.content;
    let content = typeof messageContent === "string" 
      ? messageContent 
      : "Failed to generate document";

    // Prepend metadata header to content
    const metadataHeader = `<!-- Generated by The Repo Scribe
Document Type: ${docType}
Repository: ${repoUrl}
Tone: ${tone}
Length: ${length}
Generated: ${new Date().toISOString()}
Disclaimer: This is an AI-generated template. Have a qualified attorney review before use.
-->

`;
    
    const contentWithHeader = metadataHeader + content;

    // Save to database
    if (content && typeof content === "string") {
      await saveGeneration({
        userId,
        repoUrl,
        repoName: repoMetadata.name,
        docType,
        tone,
        length,
        content: contentWithHeader,
      });
    }

    return {
      content: contentWithHeader,
      metadata: {
        repoUrl,
        repoName: repoMetadata.name,
        docType,
        tone,
        length,
      },
    };
  } catch (error: any) {
    console.error("[LLM] Generation failed:", error);

    // Handle specific error codes
    if (error.status === 429) {
      throw new Error(
        "AI rate limit reached. Please try again in a few moments."
      );
    } else if (error.status === 402) {
      throw new Error(
        "AI credits exhausted. Please add credits to your workspace."
      );
    } else {
      throw new Error("Document generation failed. Please try again.");
    }
  }
}

/**
 * Fetch repository metadata from GitHub API
 */
export async function fetchRepoMetadata(repoUrl: string) {
  // Parse owner and repo from URL
  const match = repoUrl.match(/github\.com\/([^\/]+)\/([^\/]+)\/?$/);
  if (!match) {
    throw new Error("Invalid GitHub repository URL");
  }

  const [, owner, repo] = match;
  const apiUrl = `https://api.github.com/repos/${owner}/${repo}`;

  const headers: Record<string, string> = {
    "Accept": "application/vnd.github.v3+json",
  };

  // Add GitHub token if available for higher rate limits
  if (process.env.GITHUB_TOKEN) {
    headers["Authorization"] = `token ${process.env.GITHUB_TOKEN}`;
  }

  try {
    // Fetch repo data
    const repoResponse = await fetch(apiUrl, { headers });

    if (repoResponse.status === 404) {
      throw new Error("Repository not found. Make sure it is public.");
    }

    if (!repoResponse.ok) {
      throw new Error(`GitHub API error: ${repoResponse.statusText}`);
    }

    const repoData = await repoResponse.json();

    // Fetch README
    let readme = "";
    try {
      const readmeResponse = await fetch(`${apiUrl}/readme`, { headers });
      if (readmeResponse.ok) {
        const readmeData = await readmeResponse.json();
        // Decode base64 content
        readme = Buffer.from(readmeData.content, "base64").toString("utf-8");
      }
    } catch {
      // README not found, continue
    }

    return {
      name: repoData.name,
      description: repoData.description || "",
      language: repoData.language || "",
      license: repoData.license?.name || "",
      topics: repoData.topics || [],
      readme: readme.substring(0, 2000), // Limit to first 2000 chars
    };
  } catch (error: any) {
    console.error("[GitHub API] Fetch failed:", error);
    throw error;
  }
}
